# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCCanvas.Line.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCCanvas.Line.Swift
  pod 'CCCanvas'

end
